// Generated by ReScript, PLEASE EDIT WITH CARE

import FuseJs from "fuse.js";

var Options = {};

function make(prim, prim$1) {
  return new FuseJs(prim, prim$1);
}

function search(prim, prim$1) {
  return prim.search(prim$1);
}

export {
  Options ,
  make ,
  search ,
  
}
/* fuse.js Not a pure module */
