// Generated by ReScript, PLEASE EDIT WITH CARE


function make(prim) {
  return new Worker(prim);
}

function Make(funarg) {
  return {
          make: funarg.make,
          App: {
            postMessage: (function (prim0, prim1) {
                prim0.postMessage(prim1);
              }),
            onMessage: (function (prim0, prim1) {
                prim0.onmessage = prim1;
              }),
            onError: (function (prim0, prim1) {
                prim0.onerror = prim1;
              }),
            terminate: (function (prim) {
                prim.terminate();
              })
          },
          $$Worker: {
            postMessage: (function (prim) {
                postMessage(prim);
              }),
            onMessage: (function (prim0, prim1) {
                prim0.onmessage = prim1;
              }),
            self: self,
            importScripts: (function (prim) {
                importScripts(prim);
              })
          }
        };
}

export {
  make ,
  Make ,
}
/* No side effect */
