// Generated by ReScript, PLEASE EDIT WITH CARE


var Link = {
  inline: "no-underline border-b border-night-dark hover:border-bs-purple text-inherit",
  standalone: "no-underline text-fire"
};

var H1 = {};

var H2 = {};

var H3 = {};

export {
  Link ,
  H1 ,
  H2 ,
  H3 ,
  
}
/* No side effect */
