// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "./Icon.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function DocSearch(Props) {
  var inputRef = React.useRef(null);
  var match = React.useState(function () {
        return /* Inactive */1;
      });
  var setState = match[1];
  React.useEffect((function () {
          var init = window.docsearch;
          if (init !== undefined) {
            Curry._1(init, {
                  apiKey: "d3d9d7cebf13a7b665e47cb85dc9c582",
                  indexName: "rescript-lang",
                  inputSelector: "#docsearch"
                });
          }
          
        }), []);
  React.useEffect((function () {
          var isEditableTag = function (el) {
            var match = el.tagName;
            switch (match) {
              case "INPUT" :
              case "SELECT" :
              case "TEXTAREA" :
                  return true;
              default:
                return false;
            }
          };
          var focusSearch = function (e) {
            var el = document.activeElement;
            if (el !== undefined) {
              var el$1 = Caml_option.valFromOption(el);
              if (isEditableTag(el$1)) {
                return ;
              }
              if (el$1.isContentEditable) {
                return ;
              }
              
            }
            Curry._1(setState, (function (param) {
                    return /* Active */0;
                  }));
            Belt_Option.forEach(Caml_option.nullable_to_opt(inputRef.current), (function (prim) {
                    prim.focus();
                  }));
            e.preventDefault();
          };
          var handleGlobalKeyDown = function (e) {
            var match = e.key;
            switch (match) {
              case "/" :
                  return focusSearch(e);
              case "k" :
                  if (e.ctrlKey || e.metaKey) {
                    return focusSearch(e);
                  } else {
                    return ;
                  }
              default:
                return ;
            }
          };
          window.addEventListener("keydown", handleGlobalKeyDown);
          return (function (param) {
                    window.addEventListener("keydown", handleGlobalKeyDown);
                  });
        }), [setState]);
  var clearInput = function (param) {
    Belt_Option.forEach(Caml_option.nullable_to_opt(inputRef.current), (function (el) {
            el.value = "";
          }));
  };
  var onClick = function (param) {
    Curry._1(setState, (function (param) {
            return /* Active */0;
          }));
    clearInput(undefined);
    Belt_Option.forEach(Caml_option.nullable_to_opt(inputRef.current), (function (el) {
            el.focus();
          }));
  };
  var onBlur = function (param) {
    clearInput(undefined);
    Curry._1(setState, (function (param) {
            return /* Inactive */1;
          }));
  };
  var onKeyDown = function (evt) {
    var key = evt.key;
    if (key === "Escape") {
      return Belt_Option.forEach(Caml_option.nullable_to_opt(inputRef.current), (function (el) {
                    el.blur();
                  }));
    }
    
  };
  var isActive = match[0] ? false : true;
  var activeClass = isActive ? "text-white border border-gray-60" : "";
  var activeInput = isActive ? "w-32 mr-3" : "w-0";
  return React.createElement("div", {
              className: activeClass + " bg-gray-100 border border-gray-70 hover:text-white hover:cursor-pointer flex justify-center p-2 px-3 rounded-lg",
              onClick: onClick
            }, React.createElement("input", {
                  ref: inputRef,
                  className: "transition-all ease-in-out duration-150 text-white bg-gray-100 border-none focus:outline-none " + activeInput,
                  id: "docsearch",
                  type: "text",
                  onKeyDown: onKeyDown,
                  onBlur: onBlur
                }), React.createElement(Icon.MagnifierGlass.make, {
                  className: "text-gray-60 w-5 h-5"
                }));
}

function DocSearch$Textbox(Props) {
  var id = Props.id;
  React.useEffect((function () {
          var init = window.docsearch;
          if (init !== undefined) {
            Curry._1(init, {
                  apiKey: "d3d9d7cebf13a7b665e47cb85dc9c582",
                  indexName: "rescript-lang",
                  inputSelector: "#" + id
                });
          }
          
        }), []);
  var inputRef = React.useRef(null);
  var match = React.useState(function () {
        return /* Inactive */1;
      });
  var setState = match[1];
  var onClick = function (param) {
    Curry._1(setState, (function (param) {
            return /* Active */0;
          }));
    Belt_Option.forEach(Caml_option.nullable_to_opt(inputRef.current), (function (el) {
            el.focus();
          }));
  };
  var onBlur = function (param) {
    Curry._1(setState, (function (param) {
            return /* Inactive */1;
          }));
  };
  var onKeyDown = function (evt) {
    var key = evt.key;
    if (key === "Escape") {
      return Belt_Option.forEach(Caml_option.nullable_to_opt(inputRef.current), (function (el) {
                    el.blur();
                  }));
    }
    
  };
  var isActive = match[0] ? false : true;
  var activeClass = isActive ? "text-white border border-white-80" : "opacity-75";
  var activeInput = "";
  return React.createElement("div", {
              className: activeClass + " hover:text-white hover:cursor-pointer bg-gray-80 flex items-center p-2 px-3 rounded",
              onClick: onClick
            }, React.createElement(Icon.MagnifierGlass.make, {
                  className: "w-5 h-5 mr-3"
                }), React.createElement("input", {
                  ref: inputRef,
                  className: "w-32 bg-gray-80 focus:outline-none " + activeInput,
                  id: id,
                  type: "text",
                  onKeyDown: onKeyDown,
                  onBlur: onBlur
                }));
}

var Textbox = {
  make: DocSearch$Textbox
};

var make = DocSearch;

export {
  Textbox ,
  make ,
}
/* Icon Not a pure module */
