// Generated by ReScript, PLEASE EDIT WITH CARE


var Link = {
  inline: "no-underline border-b border-gray-80 hover:border-bs-purple text-inherit",
  standalone: "no-underline text-fire"
};

var H1 = {
  $$default: "text-gray-80 font-medium tracking-tighter text-48 leading-2"
};

var H2 = {
  $$default: "text-gray-80 font-semibold text-48 leading-2"
};

var H3 = {
  $$default: "text-gray-80 font-semibold text-24 leading-2"
};

export {
  Link ,
  H1 ,
  H2 ,
  H3 ,
  
}
/* No side effect */
