/* Untyped file generated by genType. */

import * as ApiLayoutBS from './ApiLayout.bs';

export const Docs_make = ApiLayoutBS.Docs.make;

export const Prose_make = ApiLayoutBS.Prose.make;

export const Docs = ApiLayoutBS.Docs

export const Prose = ApiLayoutBS.Prose
