/* Untyped file generated by genType. */

import * as BeltDocsLayoutBS from './BeltDocsLayout.bs';

export const Docs_make = BeltDocsLayoutBS.Docs.make;

export const Prose_make = BeltDocsLayoutBS.Prose.make;

export const Docs = BeltDocsLayoutBS.Docs

export const Prose = BeltDocsLayoutBS.Prose
