// fullslug is relative to _blogposts
type pair = {slug: string, fullslug: string}

let data = Js.Array2.map(
  [
    ("release-9-1", "2021-05-07-release-9-1"),
    ("rescript-association-rebranding", "2021-03-03-rescript-association-rebranding"),
    ("release-9-0", "2021-02-09-release-9-0"),
    ("release-8-3-pt2", "2020-09-25-release-8-3-2"),
    ("release-8-3-pt1", "2020-09-25-release-8-3"),
    ("new-rescript-logo", "2020-08-28-new-rescript-logo"),
    ("bucklescript-is-rebranding", "2020-08-10-bucklescript-is-rebranding"),
    ("a-note-on-bucklescripts-future-commitments", "archive/a-note-on-bucklescripts-future-commitments"),
    ("a-small-step-for-bucklescript", "archive/a-small-step-for-bucklescript"),
    ("a-story-of-exception-encoding", "archive/a-story-of-exception-encoding"),
    ("a-story-of-lazy-encoding", "archive/a-story-of-lazy-encoding"),
    ("another-encoding", "archive/another-encoding"),
    ("arity-zero", "archive/arity-zero"),
    ("bucklescript-8-1-new-syntax", "archive/bucklescript-8-1-new-syntax"),
    ("bucklescript-release-1-0", "archive/bucklescript-release-1-0"),
    ("bucklescript-release-1-4-2", "archive/bucklescript-release-1-4-2"),
    ("bucklescript-release-1-4-3", "archive/bucklescript-release-1-4-3"),
    ("bucklescript-release-1-5-0", "archive/bucklescript-release-1-5-0"),
    ("bucklescript-release-1-5-1", "archive/bucklescript-release-1-5-1"),
    ("bucklescript-release-1-5-2", "archive/bucklescript-release-1-5-2"),
    ("bucklescript-release-1-7-0", "archive/bucklescript-release-1-7-0"),
    ("bucklescript-release-1-7-4", "archive/bucklescript-release-1-7-4"),
    ("bucklescript-release-1-7-5", "archive/bucklescript-release-1-7-5"),
    ("bucklescript-release-3-0-0", "archive/bucklescript-release-3-0-0"),
    ("bucklescript-release-3-1-0", "archive/bucklescript-release-3-1-0"),
    ("bucklescript-release-3-1-4", "archive/bucklescript-release-3-1-4"),
    ("bucklescript-release-4-0-0-pt1", "archive/bucklescript-release-4-0-0-pt1"),
    ("bucklescript-release-4-0-0-pt2", "archive/bucklescript-release-4-0-0-pt2"),
    ("bucklescript-release-4-0-17", "archive/bucklescript-release-4-0-17"),
    ("bucklescript-release-4-0-8", "archive/bucklescript-release-4-0-8"),
    ("bucklescript-release-5-0-1", "archive/bucklescript-release-5-0-1"),
    ("bucklescript-release-5-0-4", "archive/bucklescript-release-5-0-4"),
    ("bucklescript-release-5-0-5", "archive/bucklescript-release-5-0-5"),
    ("bucklescript-release-5-0", "archive/bucklescript-release-5-0"),
    ("bucklescript-release-5-1-0", "archive/bucklescript-release-5-1-0"),
    ("bucklescript-release-5-2-0", "archive/bucklescript-release-5-2-0"),
    ("bucklescript-release-6-0", "archive/bucklescript-release-6-0"),
    ("bucklescript-release-7-0-2", "archive/bucklescript-release-7-0-2"),
    ("bucklescript-release-7-1-0", "archive/bucklescript-release-7-1-0"),
    ("bucklescript-release-7-2", "archive/bucklescript-release-7-2"),
    ("bucklescript-release-7-3", "archive/bucklescript-release-7-3"),
    ("bucklescript-release-8-1-1", "archive/bucklescript-release-8-1-1"),
    ("bucklescript-release-8-2", "archive/bucklescript-release-8-2"),
    ("bucklescript-roadmap-q3-4-2018", "archive/bucklescript-roadmap-q3-4-2018"),
    ("feature-preview-variadic", "archive/feature-preview-variadic"),
    ("ffi-overview", "archive/ffi-overview"),
    ("generalize-uncurry", "archive/generalize-uncurry"),
    ("loading-stdlib-in-memory", "archive/loading-stdlib-in-memory"),
    ("overview-of-new_encoding", "archive/overview-of-new_encoding"),
    ("scalable", "archive/scalable"),
    ("state-of-reasonml-org-2020-q2-pt1", "archive/state-of-reasonml-org-2020-q2-pt1"),
    ("state-of-reasonml-org-2020-q2-pt2", "archive/state-of-reasonml-org-2020-q2-pt2"),
    ("state-of-reasonml-org-2020-q2-pt3", "archive/state-of-reasonml-org-2020-q2-pt3"),
    ("state-of-reasonml-org-2020-q2-pt4", "archive/state-of-reasonml-org-2020-q2-pt4"),
    ("string-literal-types-in-reason", "archive/string-literal-types-in-reason"),
    ("union-types-in-bucklescript", "archive/union-types-in-bucklescript"),
    ("whats-new-in-7-pt1", "archive/whats-new-in-7-pt1"),
    ("whats-new-in-7-pt2", "archive/whats-new-in-7-pt2"),
    ("editor-support-custom-operators-and-more", "2020-11-17-editor-support-custom-operators-and-more"),
    ("editor-support-release-1-0", "2020-11-26-editor-support-release-1-0"),
    ("bucklescript-release-8-4", "2020-12-07-release-8-4"),
  ],
  ((slug, fullslug)) => {slug: slug, fullslug: fullslug},
)
