// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function useEval(param) {
  var workerRef = React.useRef(undefined);
  React.useEffect((function () {
          var worker = (new Worker(new URL("../worker.js", import.meta.url)));
          workerRef.current = Caml_option.some(worker);
          worker.onmessage = (function (evt) {
              console.log("value: " + evt.data);
              
            });
          console.log(worker);
          return (function (param) {
                    Belt_Option.map(workerRef.current, (function (worker) {
                            worker.terminate();
                            
                          }));
                    
                  });
        }), []);
  var handleWork = React.useCallback((function (param) {
          return Belt_Option.forEach(workerRef.current, (function (worker) {
                        worker.postMessage(100000);
                        
                      }));
        }), []);
  return [
          workerRef,
          handleWork
        ];
}

function EvalTest$default(Props) {
  var match = useEval(undefined);
  return React.createElement("div", undefined, React.createElement("p", undefined, "Do work in a WebWorker!"), React.createElement("button", {
                  onClick: match[1]
                }, "Calculate PI"));
}

var $$default = EvalTest$default;

export {
  useEval ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
