// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Eval from "./Eval.mjs";
import * as Curry from "rescript/lib/es6/curry.js";

Curry._1(Eval.EvalWorker.$$Worker.addEventListener, (function (msg) {
        console.log(msg);
        
      }));

export {
  
}
/*  Not a pure module */
