// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Markdown from "../components/Markdown.mjs";
import * as DocsLayout from "./DocsLayout.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

var tocData = (require('index_data/community_toc.json'));

var CommunityLayout = DocsLayout.Make({
      tocData: tocData
    });

function CommunityLayout$1(Props) {
  var frontmatter = Props.frontmatter;
  var componentsOpt = Props.components;
  var children = Props.children;
  var components = componentsOpt !== undefined ? Caml_option.valFromOption(componentsOpt) : Markdown.$$default;
  var tmp = {
    breadcrumbs: {
      hd: {
        name: "Community",
        href: "/community"
      },
      tl: /* [] */0
    },
    title: "Community",
    metaTitleCategory: "ReScript Community",
    components: components,
    theme: "Reason",
    children: children
  };
  if (frontmatter !== undefined) {
    tmp.frontmatter = Caml_option.valFromOption(frontmatter);
  }
  return React.createElement(CommunityLayout.make, tmp);
}

var make = CommunityLayout$1;

export {
  make ,
}
/* CommunityLayout Not a pure module */
