// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mdx from "../common/Mdx.mjs";
import * as Meta from "../components/Meta.mjs";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Footer from "../components/Footer.mjs";
import * as Markdown from "../components/Markdown.mjs";
import * as Navigation from "../components/Navigation.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function LandingPageLayout$CallToActionButton(Props) {
  var children = Props.children;
  return React.createElement("button", {
              className: "transition-colors duration-200 inline-block text-base text-white hover:bg-water-70 hover:text-white hover:border-water-70 bg-water rounded border border-water px-5 py-2"
            }, children);
}

function LandingPageLayout$Intro(Props) {
  return React.createElement("div", {
              className: "flex flex-col items-center"
            }, React.createElement("h1", {
                  className: "text-56 text-gray-95 tracking-tight leading-2 font-semibold text-center",
                  style: {
                    maxWidth: "54rem"
                  }
                }, "A simple and fast language for JavaScript developers"), React.createElement("h2", {
                  className: "text-gray-40 text-center my-4"
                }, "ReScript looks like JS, acts like JS, and compiles to the highest quality of clean, readable and performant JS, directly runnable in browsers and Node."), React.createElement(LandingPageLayout$CallToActionButton, {
                  children: "Get started"
                }));
}

function LandingPageLayout$PlaygroundHero(Props) {
  return React.createElement("section", {
              className: "relative flex justify-center px-12 bg-gray-10",
              style: {
                height: "35rem"
              }
            }, React.createElement("div", {
                  className: "bg-gray-90 max-w-740 w-full -mt-12",
                  style: {
                    height: "30rem"
                  }
                }, "Playground Widget etc."));
}

function LandingPageLayout$MainUSP$Item(Props) {
  var title = Props.title;
  var paragraph = Props.paragraph;
  return React.createElement("div", {
              className: "w-full",
              style: {
                maxWidth: "30rem"
              }
            }, React.createElement("h3", {
                  className: "text-gray-10 mt-16 mb-6 text-32 leading-1 font-semibold",
                  style: {
                    maxWidth: "25rem"
                  }
                }, title), React.createElement("div", {
                  className: "text-gray-60 text-16"
                }, paragraph));
}

var item1 = React.createElement(LandingPageLayout$MainUSP$Item, {
      title: "The fastest build system on the web",
      paragraph: "ReScript cares about a consistent and fast feedback loop for any\n            codebase size. No need for memory hungry build processes, and no\n            corrupted caches. Switch branches as you please without worrying\n            about stale caches or wrong type information."
    });

var item2 = React.createElement(LandingPageLayout$MainUSP$Item, {
      title: "Robust Type System",
      paragraph: " Every ReScript app is fully typed and provides\n      correct type information to any given value. We prioritize simpler types\n      / discourage complex types for the sake of clarity and easy debugability.\n      No `any`, no magic types, no surprise `undefined`.\n      "
    });

var item3 = React.createElement(LandingPageLayout$MainUSP$Item, {
      title: "Seamless JS Integration",
      paragraph: "Use any library from javascript, export rescript\n      libraries to javascript, generate typescript and flow types, etc. It's\n      like you've never left the good parts of javascript at all."
    });

var items = [
  item1,
  item2,
  item3
];

var tabs = [
  "Fast and Simple",
  "Robust Type System",
  "Seamless JS Integration"
];

function LandingPageLayout$MainUSP(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setSelectedIndex = match[1];
  var selectedIndex = match[0];
  return React.createElement("section", {
              className: "flex items-stretch w-full"
            }, React.createElement("div", {
                  className: "pl-32 bg-gray-90 pb-32 w-full text-white-80"
                }, React.createElement("div", {
                      className: "flex justify-between mt-6 pr-20 w-full"
                    }, tabs.map(function (tabTitle, i) {
                          var className = i === selectedIndex ? "text-fire-50 text-xl border-b-2 border-fire-50" : "text-xl text-gray-80";
                          return React.createElement("button", {
                                      className: className,
                                      onClick: (function (_evt) {
                                          return Curry._1(setSelectedIndex, (function (param) {
                                                        return i;
                                                      }));
                                        })
                                    }, tabTitle);
                        })), React.createElement("div", {
                      className: "mt-20"
                    }, items[selectedIndex])), React.createElement("div", {
                  className: "bg-fire-40 h-full w-full flex flex-col",
                  style: {
                    maxWidth: "18.5rem"
                  }
                }, React.createElement("div", {
                      className: "flex-grow"
                    })));
}

function LandingPageLayout$TrustedBy(Props) {
  return React.createElement("section", {
              className: "my-20"
            }, React.createElement("h3", {
                  className: "text-42 text-gray-42 tracking-tight leading-2 font-semibold text-center max-w-576 mx-auto"
                }, "Trusted by developers around the world"), React.createElement("div", {
                  className: "flex justify-between max-w-lg mx-auto mt-16"
                }, [
                    "Facebook",
                    "Rohea",
                    "Beop",
                    "Travel World",
                    "Pupilfirst",
                    "NomadicLabs"
                  ].map(function (company) {
                      return React.createElement("div", {
                                  key: company
                                }, company);
                    })), React.createElement("div", {
                  className: "text-center mt-16 text-sm"
                }, "and many more…"));
}

var cards = [
  {
    imgSrc: "/static/ic_manual@2x.png",
    title: "Language Manual",
    descr: "Look up the basics: reference for all language features",
    link: "/"
  },
  {
    imgSrc: "/static/ic_rescript_react@2x.png",
    title: "ReScript + React",
    descr: "First Class bindings for ReactJS. Developed for small and big ass scale projects.",
    link: "/"
  },
  {
    imgSrc: "/static/ic_manual@2x.png",
    title: "Add ReScript to an existing project",
    descr: "This guide will help you to transfer your project without hassle.",
    link: "/"
  },
  {
    imgSrc: "/static/ic_gentype@2x.png",
    title: "TypeScript Integration",
    descr: "Integrate TypeScript and Flow seamlessly and with ease.",
    link: "/"
  }
];

function LandingPageLayout$CuratedResources(Props) {
  return React.createElement("section", {
              className: "bg-gray-90 w-full pb-40"
            }, React.createElement("h2", {
                  className: "text-gray-10 my-20 text-32 leading-2 font-semibold max-w-md mx-auto text-center"
                }, "Carefully curated resources to start or advance your ReScript projects"), React.createElement("div", undefined, React.createElement("div", {
                      className: "uppercase text-sm text-center mb-20"
                    }, "guides and docs"), React.createElement("div", {
                      className: "flex justify-between max-w-2xl mx-auto"
                    }, cards.map(function (card) {
                          return React.createElement("div", {
                                      className: "bg-gray-95 px-5 pb-8 relative rounded-xl",
                                      style: {
                                        maxWidth: "250px"
                                      }
                                    }, React.createElement("img", {
                                          className: "h-12 absolute mt-5",
                                          src: card.imgSrc
                                        }), React.createElement("h5", {
                                          className: "text-gray-10 font-semibold mt-32 h-12"
                                        }, card.title), React.createElement("div", {
                                          className: "text-gray-40 mt-8 text-sm"
                                        }, card.descr));
                        }))));
}

function LandingPageLayout(Props) {
  var componentsOpt = Props.components;
  var children = Props.children;
  var components = componentsOpt !== undefined ? Caml_option.valFromOption(componentsOpt) : Markdown.$$default;
  var overlayState = React.useState(function () {
        return false;
      });
  return React.createElement(React.Fragment, undefined, React.createElement(Meta.make, {}), React.createElement("div", {
                  className: "mt-4 xs:mt-16"
                }, React.createElement("div", {
                      className: "text-gray-80 text-lg"
                    }, React.createElement(Navigation.make, {
                          overlayState: overlayState
                        }), React.createElement("div", {
                          className: "absolute top-16 w-full"
                        }, React.createElement("div", {
                              className: "relative flex xs:justify-center overflow-hidden pb-32"
                            }, React.createElement("main", {
                                  className: "mt-10 min-w-320 lg:align-center w-full"
                                }, React.createElement(Mdx.Provider.make, {
                                      components: components,
                                      children: React.createElement("div", {
                                            className: "flex justify-center"
                                          }, React.createElement("div", {
                                                className: "w-full flex flex-col"
                                              }, React.createElement("div", {
                                                    className: "mt-12 max-w-740 self-center"
                                                  }, React.createElement(LandingPageLayout$Intro, {})), React.createElement("div", {
                                                    className: "mt-16 w-full self-center"
                                                  }, React.createElement(LandingPageLayout$PlaygroundHero, {})), React.createElement("div", {
                                                    className: "mt-16"
                                                  }, React.createElement(LandingPageLayout$MainUSP, {
                                                        children: "test"
                                                      })), React.createElement(LandingPageLayout$TrustedBy, {}), React.createElement(LandingPageLayout$CuratedResources, {}), children))
                                    }))), React.createElement(Footer.make, {})))));
}

var make = LandingPageLayout;

export {
  make ,
  
}
/* item1 Not a pure module */
